### ISSUE TITLE
rc1 support?

### ISSUE THREAD

**Issue by smnbbrv** [sagarrabadiya/ng2-resource#2]
hello,

currently the package requires a peer dependency angular beta:
├── UNMET PEER DEPENDENCY angular2@^2.0.0-beta.7

Would this be fixed?

**Comment by sagarrabadiya** [comment]
yes actually i havent got enough time to add more functionality and update angular 2 but i will update it soon thanks for reviewing 😀

**Comment by smnbbrv** [comment]
well, I think it is going to be useful to have this library :)

**Comment by sagarrabadiya** [comment]
@smnbbrv i have released 1.1 which has support for angular rc3 so i think it should fix now, update your package.json to include 1.1.0 version and let me know if it works so i will close the issue! thanks.

**Comment by smnbbrv** [comment]
Thanks! Unfortunately I don't really have time to check it in the nearest future, if it's fixed close it :)
